#ifndef __GPUCC_COMPILER_DXC_WIN32_H__
#define __GPUCC_COMPILER_DXC_WIN32_H__

#pragma once

#ifndef GPUCC_NO_INCLUDES
#   ifndef __GPUCC_DXCCOMPILERAPI_WIN32_H__
#       include "win32/dxccompilerapi_win32.h"
#   endif
#endif

/* @summary Cast a GPUCC_PROGRAM_COMPILER* to a GPUCC_COMPILER_DXC_WIN32*.
 */
#ifndef gpuccCompilerDxc_
#define gpuccCompilerDxc_(_c)                                                  \
    ((GPUCC_COMPILER_DXC_WIN32*)(_c))
#endif

/* @summary Cast a GPUCC_PROGRAM_BYTECODE* to a GPUCC_BYTECODE_DXC_WIN32*.
 */
#ifndef gpuccBytecodeDxc_
#define gpuccBytecodeDxc_(_b)                                                  \
    ((GPUCC_BYTECODE_DXC_WIN32*)(_b))
#endif

/* @summary Define the maximum number of arguments that can be passed to the dxc compiler.
 * A list of arguments can be displayed by running `dxc -help`.
 */
#ifndef GPUCC_COMPILER_DXC_WIN32_MAX_ARGS
#define GPUCC_COMPILER_DXC_WIN32_MAX_ARGS                                     32 
#endif

// TODO: Good example code here:
// https://blogs.msdn.microsoft.com/marcelolr/2017/03/27/directx-compiler-apis/

/* @summary Define the data maintained by an instance of the dxc compiler.
 * This compiler type can emit both DXIL (Direct3D) and SPIR-V (Vulkan and OpenGL 4.5+) bytecode.
 */
typedef struct GPUCC_COMPILER_DXC_WIN32 {
    GPUCC_PROGRAM_COMPILER_BASE   CommonFields;                                /* This must be the first field of any compiler type. */
    DXCCOMPILERAPI_DISPATCH      *DispatchTable;                               /* A pointer to the dxcompiler dispatch table maintained by the process context. */
    IDxcLibrary                  *DxcLibrary;                                  /* The IDxcLibrary interface used to create blobs for specifying source code, etc. */
    IDxcCompiler                 *DxcCompiler;                                 /* The IDxcCompiler interface instance used to compile code. */
    DxcDefine                    *DefineArray;                                 /* An array of DxcDefine (WCHAR versions of D3D_SHADER_MACRO) specifying the symbols and values defined for the compiler. */
    uint32_t                      DefineCount;                                 /* The number of valid elements in the DxcDefine array. */
    int32_t                       TargetRuntime;                               /* One of the values of the GPUCC_TARGET_RUNTIME enumeration specifying the target runtime for shaders built by the compiler. */
    WCHAR                        *ShaderModel;                                 /* A nul-terminated string specifying the Direct3D shader model. */
    WCHAR const                 **ClArguments;                                 /* An array of nul-terminated string arguments passed to the compiler. */
    uint32_t                      ArgumentCount;                               /* The number of items in the ClArguments array. */
} GPUCC_COMPILER_DXC_WIN32;

/* @summary Define the data maintained by a single HLSL program bytecode container generated by the dxc compiler.
 * The bytecode may be either DXIL (Direct3D) or SPIR-V (Vulkan and OpenGL 4.5+) format.
 */
typedef struct GPUCC_BYTECODE_DXC_WIN32 {
    GPUCC_PROGRAM_BYTECODE_BASE   CommonFields;                                /* This must be the first field of any bytecode container type. */
    IDxcBlob                     *CodeBuffer;                                  /* The buffer for storing the compiled bytecode. This is NULL unless the compilation succeeds. */
    IDxcBlobEncoding             *ErrorLog;                                    /* The blob containing the output from the compilation. */
} GPUCC_BYTECODE_DXC_WIN32;

#ifdef __cplusplus
extern "C" {
#endif

/* @summary Allocate and initialize a bytecode container for DXIL or SPIR-V bytecode generated by the dxc compiler.
 * @param compiler A pointer to an instance of GPUCC_COMPILER_DXC_WIN32.
 * @return A pointer to the bytecode container, of type GPUCC_BYTECODE_DXC_WIN32, or NULL if the allocation failed.
 */
GPUCC_API(struct GPUCC_PROGRAM_BYTECODE*)
gpuccCreateProgramBytecodeDxc
(
    struct GPUCC_PROGRAM_COMPILER *compiler
);

/* @summary Release all resources associated with a dxc program bytecode container.
 * @param bytecode A pointer to an instance of GPUCC_BYTECODE_DXC_WIN32.
 */
GPUCC_API(void)
gpuccDeleteProgramBytecodeDxc
(
    struct GPUCC_PROGRAM_BYTECODE *bytecode
);

/* @summary Compile GPU program source code into intermediate bytecode using the dxc compiler.
 * The caller is responsible for processing any source code includes and supplying the full resulting source code in the source_code buffer.
 * The function blocks the calling thread until compilation has completed.
 * The resulting bytecode will be DXIL by default, unless the caller specified GPUCC_BYTECODE_TYPE_SPIRV when the compiler was created.
 * @param container The container that will be used to store the program bytecode, of type GPUCC_BYTECODE_FXC_WIN32.
 * @param source_code Pointer to a buffer containing UTF-8 encoded GPU program source code.
 * @param source_size The number of bytes of program source code in the spurce_code buffer.
 * @oaram source_path A nul-terminated UTF-8 string specifying the path to the source file, for use in log output. This value may be NULL.
 * @param entry_point A nul-terminated string specifying the program entry point.
 * @return The result of the compilation. Use the gpuccSuccess and gpuccFailure macros to determine whether compilation was successful.
 */
GPUCC_API(struct GPUCC_RESULT)
gpuccCompileBytecodeDxc
(
    struct GPUCC_PROGRAM_BYTECODE *container, 
    char const                  *source_code, 
    uint64_t                     source_size, 
    char const                  *source_path, 
    char const                  *entry_point
);

/* @summary Allocate and initialize a new compiler record for accessing the dxc compiler.
 * @param config Data used to configure the compiler instance.
 * @return A pointer to the compiler, or NULL if an error occurred.
 */
GPUCC_API(struct GPUCC_PROGRAM_COMPILER*)
gpuccCreateCompilerDxc
(
    struct GPUCC_PROGRAM_COMPILER_INIT *config
);

#ifdef __cplusplus
}; /* extern "C" */
#endif

#endif


